const EXT = globalThis.browser || globalThis.chrome;
const $=(id)=>document.getElementById(id);let settings;let toastTimer;
const ACCENTS={ivorian:["#6aa6cd","106,166,205","#397bac"],ocean:["#60a5fa","96,165,250","#2563a8"],lavender:["#a78bfa","167,139,250","#8067d5"],sage:["#69b89a","105,184,154","#3c8c70"]};
function formatBytes(bytes){const v=Number(bytes||0);if(v<=0)return"0 KB";if(v<1024)return`${Math.round(v)} B`;if(v<1024**2)return`${(v/1024).toFixed(1)} KB`;if(v<1024**3)return`${(v/1024**2).toFixed(1)} MB`;return`${(v/1024**3).toFixed(2)} GB`}
function applyTheme(){const[a,rgb,strong]=ACCENTS[settings.accent]||ACCENTS.ivorian;document.documentElement.dataset.theme=settings.theme||"system";document.documentElement.style.setProperty("--accent",a);document.documentElement.style.setProperty("--accent-rgb",rgb);document.documentElement.style.setProperty("--accent-strong",strong)}
function showToast(){clearTimeout(toastTimer);$("saveToast").classList.add("show");toastTimer=setTimeout(()=>$("saveToast").classList.remove("show"),1000)}
async function save(patch){settings={...settings,...patch};if(patch.customConfig)settings.customConfig={...settings.customConfig,...patch.customConfig};await EXT.runtime.sendMessage({type:"SAVE_SETTINGS",settings:patch});applyTheme();renderSelections();showToast()}
function renderSelections(){document.querySelectorAll("[data-theme]").forEach(b=>b.classList.toggle("active",b.dataset.theme===settings.theme));document.querySelectorAll("[data-accent]").forEach(b=>b.classList.toggle("active",b.dataset.accent===settings.accent));$("defaultMode").value=settings.defaultMode;$("rememberSiteMode").checked=!!settings.rememberSiteMode;$("showBadge").checked=!!settings.showBadge;const c=settings.customConfig;$("customImages").value=c.images;$("customMedia").checked=!!c.media;$("customFonts").checked=!!c.fonts;$("customFrames").value=c.frames;$("customMotion").value=c.motionLevel||(c.reduceMotion===false?"none":"reduce");$("customAutoplay").checked=!!c.pauseAutoplay;$("customFocusShield").checked=!!c.focusShield}
async function refreshStats(){const s=await EXT.runtime.sendMessage({type:"GET_GLOBAL_STATS"});$("statSaved").textContent=formatBytes(s.measuredBytesSaved);$("statPages").textContent=s.pagesOptimized;$("statRequests").textContent=s.requestsSaved;$("statBest").textContent=`${s.bestSavingPercent||0}%`}
async function init(){settings=await EXT.runtime.sendMessage({type:"GET_SETTINGS"});applyTheme();renderSelections();await refreshStats()}
document.querySelectorAll("[data-theme]").forEach(b=>b.addEventListener("click",()=>save({theme:b.dataset.theme})));document.querySelectorAll("[data-accent]").forEach(b=>b.addEventListener("click",()=>save({accent:b.dataset.accent})));$("defaultMode").addEventListener("change",e=>save({defaultMode:e.target.value}));$("rememberSiteMode").addEventListener("change",e=>save({rememberSiteMode:e.target.checked}));$("showBadge").addEventListener("change",e=>save({showBadge:e.target.checked}));const customPatch=()=>({customConfig:{images:$("customImages").value,media:$("customMedia").checked,fonts:$("customFonts").checked,frames:$("customFrames").value,motionLevel:$("customMotion").value,pauseAutoplay:$("customAutoplay").checked,focusShield:$("customFocusShield").checked,smartFilter:$("customFocusShield").checked}});["customImages","customMedia","customFonts","customFrames","customMotion","customAutoplay","customFocusShield"].forEach(id=>$(id).addEventListener("change",()=>save(customPatch())));$("resetStats").addEventListener("click",async()=>{if(!confirm("Reset WebLite's measured impact stats?"))return;await EXT.runtime.sendMessage({type:"RESET_GLOBAL_STATS"});await refreshStats();showToast()});$("openTutorial").addEventListener("click",()=>EXT.runtime.sendMessage({type:"OPEN_TUTORIAL"}));init();
